name:                git-tools
version:             0.1.0.0
github:              "githubuser/git-tools"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/git-tools#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 0.63
- directory >= 1.3.6.2
- vty >= 5.33
- text >= 1.2.5.0
- process >= 1.6.13.2
- mtl >= 2.2.2
- word-wrap >= 0.5
- microlens-platform >= 0.4.3.4
- lens >= 5.2.3
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gbt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-tools

tests:
  git-tools-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    #  - '"-with-rtsopts=-N -qg"'
    dependencies:
    - git-tools
    - hspec >= 2.10.10
    - hspec-expectations-lifted
